
# This file is automatically generated, you probably don't want to edit this

anovaNPOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaNPOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            group = NULL,
            jttest = FALSE,
            dunnpairs = FALSE,
            coimpairs = FALSE,
            dscfpairs = FALSE,
            postHocCorr = NULL,
            miss = "perAnalysis",
            qq = FALSE, ...) {

            super$initialize(
                package="nptests",
                name="anovaNP",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                required=TRUE,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=TRUE,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..jttest <- jmvcore::OptionBool$new(
                "jttest",
                jttest,
                default=FALSE)
            private$..dunnpairs <- jmvcore::OptionBool$new(
                "dunnpairs",
                dunnpairs,
                default=FALSE)
            private$..coimpairs <- jmvcore::OptionBool$new(
                "coimpairs",
                coimpairs,
                default=FALSE)
            private$..dscfpairs <- jmvcore::OptionBool$new(
                "dscfpairs",
                dscfpairs,
                default=FALSE)
            private$..postHocCorr <- jmvcore::OptionNMXList$new(
                "postHocCorr",
                postHocCorr,
                options=list(
                    "none",
                    "bonf",
                    "sidak",
                    "holm"))
            private$..miss <- jmvcore::OptionList$new(
                "miss",
                miss,
                options=list(
                    "perAnalysis",
                    "listwise"),
                default="perAnalysis")
            private$..qq <- jmvcore::OptionBool$new(
                "qq",
                qq,
                default=FALSE)

            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..jttest)
            self$.addOption(private$..dunnpairs)
            self$.addOption(private$..coimpairs)
            self$.addOption(private$..dscfpairs)
            self$.addOption(private$..postHocCorr)
            self$.addOption(private$..miss)
            self$.addOption(private$..qq)
        }),
    active = list(
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        jttest = function() private$..jttest$value,
        dunnpairs = function() private$..dunnpairs$value,
        coimpairs = function() private$..coimpairs$value,
        dscfpairs = function() private$..dscfpairs$value,
        postHocCorr = function() private$..postHocCorr$value,
        miss = function() private$..miss$value,
        qq = function() private$..qq$value),
    private = list(
        ..deps = NA,
        ..group = NA,
        ..jttest = NA,
        ..dunnpairs = NA,
        ..coimpairs = NA,
        ..dscfpairs = NA,
        ..postHocCorr = NA,
        ..miss = NA,
        ..qq = NA)
)

anovaNPResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaNPResults",
    inherit = jmvcore::Group,
    active = list(
        kwTable = function() private$.items[["kwTable"]],
        jtTable = function() private$.items[["jtTable"]],
        postHoc = function() private$.items[["postHoc"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Way ANOVA On Ranks")
            self$add(jmvcore::Table$new(
                options=options,
                name="kwTable",
                title="Kruskal-Wallis",
                rows="(deps)",
                clearWith=list(
                    "group",
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `superTitle`="Statistic", 
                        `combineBelow`=TRUE, 
                        `title`="H", 
                        `type`="number"),
                    list(
                        `name`="sties", 
                        `superTitle`="Statistic", 
                        `combineBelow`=TRUE, 
                        `title`="H/<sub>ties</sub>", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pval", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="es", 
                        `title`="\u03B5\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jtTable",
                title="Jonckhere-Terpstra",
                rows="(deps)",
                visible="(jttest)",
                clearWith=list(
                    "group",
                    "miss"),
                columns=list(
                    list(
                        `name`="name", 
                        `title`="", 
                        `content`="($key)", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="T<sub>JT</sub>", 
                        `type`="number"),
                    list(
                        `name`="seval", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="zval", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="pval", 
                        `superTitle`="Alternative Hypothesis", 
                        `combineBelow`=TRUE, 
                        `title`="two.sided", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pvald", 
                        `superTitle`="Alternative Hypothesis", 
                        `combineBelow`=TRUE, 
                        `title`="decreasing", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pvali", 
                        `superTitle`="Alternative Hypothesis", 
                        `combineBelow`=TRUE, 
                        `title`="increasing", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="postHoc",
                title="Post Hoc Tests",
                items="(deps)",
                visible="(dscfpairs || dunnpairs || coimpairs)",
                clearWith=list(
                    "group",
                    "miss"),
                template=jmvcore::Table$new(
                    options=options,
                    title="Post Hoc Comparisons - $key",
                    rows="(pairs)",
                    columns=list(
                        list(
                            `name`="pair1", 
                            `title`="", 
                            `content`="($key)", 
                            `type`="text", 
                            `combineBelow`=TRUE, 
                            `visible`="(dscfpairs || dunnpairs || coimpairs)"),
                        list(
                            `name`="pair2", 
                            `title`="", 
                            `type`="text", 
                            `visible`="(dscfpairs || dunnpairs || coimpairs)"),
                        list(
                            `name`="test[dunn]", 
                            `title`="", 
                            `content`="Dunn's z", 
                            `type`="text", 
                            `combineBelow`=TRUE, 
                            `visible`="(dunnpairs)"),
                        list(
                            `name`="stat[dunn]", 
                            `title`="Statistic", 
                            `type`="number", 
                            `visible`="(dunnpairs)"),
                        list(
                            `name`="pval[dunn]", 
                            `title`="p", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(dunnpairs)"),
                        list(
                            `name`="pnone[dunn]", 
                            `title`="p<sub>none</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(dunnpairs && postHocCorr:none)"),
                        list(
                            `name`="pbonf[dunn]", 
                            `title`="p<sub>bonferroni</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(dunnpairs && postHocCorr:bonf)"),
                        list(
                            `name`="psidak[dunn]", 
                            `title`="p<sub>sidak</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(dunnpairs && postHocCorr:sidak)"),
                        list(
                            `name`="pholm[dunn]", 
                            `title`="p<sub>holm</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(dunnpairs && postHocCorr:holm)"),
                        list(
                            `name`="test[coim]", 
                            `title`="", 
                            `content`="Conover-Iman t", 
                            `type`="text", 
                            `combineBelow`=TRUE, 
                            `visible`="(coimpairs)"),
                        list(
                            `name`="stat[coim]", 
                            `title`="Statistic", 
                            `type`="number", 
                            `visible`="(coimpairs)"),
                        list(
                            `name`="pval[coim]", 
                            `title`="p", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(coimpairs)"),
                        list(
                            `name`="pnone[coim]", 
                            `title`="p<sub>none</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(coimpairs && postHocCorr:none)"),
                        list(
                            `name`="pbonf[coim]", 
                            `title`="p<sub>bonferroni</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(coimpairs && postHocCorr:bonf)"),
                        list(
                            `name`="psidak[coim]", 
                            `title`="p<sub>sidak</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(coimpairs && postHocCorr:sidak)"),
                        list(
                            `name`="pholm[coim]", 
                            `title`="p<sub>holm</sub>", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(coimpairs && postHocCorr:holm)"),
                        list(
                            `name`="test[dscf]", 
                            `title`="", 
                            `content`="DSCF q", 
                            `type`="text", 
                            `combineBelow`=TRUE, 
                            `visible`="(dscfpairs)"),
                        list(
                            `name`="stat[dscf]", 
                            `title`="Statistic", 
                            `type`="number", 
                            `visible`="(dscfpairs)"),
                        list(
                            `name`="pval[dscf]", 
                            `title`="p", 
                            `type`="number", 
                            `format`="zto,pvalue", 
                            `visible`="(dscfpairs)"),
                        list(
                            `name`="pnone[dscf]", 
                            `title`="p<sub>none</sub>", 
                            `type`="number", 
                            `combineBelow`=TRUE, 
                            `format`="zto,pvalue", 
                            `visible`="(dscfpairs && postHocCorr:none)"),
                        list(
                            `name`="pbonf[dscf]", 
                            `title`="p<sub>bonferroni</sub>", 
                            `type`="number", 
                            `combineBelow`=TRUE, 
                            `format`="zto,pvalue", 
                            `visible`="(dscfpairs && postHocCorr:bonf)"),
                        list(
                            `name`="psidak[dscf]", 
                            `title`="p<sub>sidak</sub>", 
                            `type`="number", 
                            `combineBelow`=TRUE, 
                            `format`="zto,pvalue", 
                            `visible`="(dscfpairs && postHocCorr:sidak)"),
                        list(
                            `name`="pholm[dscf]", 
                            `title`="p<sub>holm</sub>", 
                            `type`="number", 
                            `combineBelow`=TRUE, 
                            `format`="zto,pvalue", 
                            `visible`="(dscfpairs && postHocCorr:holm)")))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(deps)",
                clearWith=list(
                    "group",
                    "miss"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        qq = function() private$.items[["qq"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="qq",
                                width=600,
                                height=400,
                                requiresData=TRUE,
                                visible="(qq)",
                                renderFun=".qq",
                                clearWith=list()))}))$new(options=options)))}))

anovaNPBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "anovaNPBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "nptests",
                name = "anovaNP",
                version = c(1,0,2),
                options = options,
                results = anovaNPResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' One-Way ANOVA On Ranks
#'
#' The Kruskal-Wallis test is used to explore the relationship between a 
#' continuous dependent variable, and a categorical explanatory variable. It 
#' is analagous to ANOVA, but with the advantage of being non-parametric and 
#' having fewer assumptions. However, it has the limitation that it can only 
#' test a single explanatory variable at a time. Conover-Iman and Dunn test 
#' are available to report results across multiple pairwise comparisons.
#' 
#'
#' @examples
#' data('ToothGrowth')
#'
#' anovaNP(formula = len ~ dose, data=ToothGrowth)
#'
#' #
#' #  ONE-WAY ANOVA (NON-PARAMETRIC)
#' #
#' #  Kruskal-Wallis
#' #  -------------------------------
#' #           X²      df    p
#' #  -------------------------------
#' #    len    40.7     2    < .001
#' #  -------------------------------
#' #
#'
#' @param data the data as a data frame
#' @param deps the dependent variables (not necessary when using a formula,
#'   see the examples)
#' @param group a string naming the grouping or independent variable in
#'   \code{data}
#' @param jttest \code{TRUE} or \code{FALSE} (default), perform
#'   Jonckhere-Terpstra trend test
#' @param dunnpairs \code{TRUE} or \code{FALSE} (default), perform Dunn's
#'   pairwise comparisons
#' @param coimpairs \code{TRUE} or \code{FALSE} (default), perform
#'   Conover-Iman pairwise comparisons
#' @param dscfpairs \code{TRUE} or \code{FALSE} (default), perform DSCF
#'   pairwise comparisons
#' @param postHocCorr one or more of \code{'none'}, \code{'bonferroni'},
#'   \code{'sidak'}, and \code{'holm'} Post Hoc corrections respectively
#' @param miss \code{'perAnalysis'} or \code{'listwise'}, how to handle
#'   missing values; \code{'perAnalysis'} excludes missing values for individual
#'   dependent variables, \code{'listwise'} excludes a row from all analyses if
#'   one of its entries is missing.
#' @param qq \code{TRUE} or \code{FALSE} (default), provide a Q-Q plot of
#'   residuals
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$kwTable} \tab \tab \tab \tab \tab a table of the test results \cr
#'   \code{results$jtTable} \tab \tab \tab \tab \tab a table of the test results \cr
#'   \code{results$postHoc} \tab \tab \tab \tab \tab an array of pairwise comparison tables \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of groups of plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$kwTable$asDF}
#'
#' \code{as.data.frame(results$kwTable)}
#'
#' @export
anovaNP <- function(
    data,
    deps,
    group,
    jttest = FALSE,
    dunnpairs = FALSE,
    coimpairs = FALSE,
    dscfpairs = FALSE,
    postHocCorr,
    miss = "perAnalysis",
    qq = FALSE,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("anovaNP requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(deps))
            deps <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                required=TRUE)
        if (missing(group))
            group <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                subset="1")
    }

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- anovaNPOptions$new(
        deps = deps,
        group = group,
        jttest = jttest,
        dunnpairs = dunnpairs,
        coimpairs = coimpairs,
        dscfpairs = dscfpairs,
        postHocCorr = postHocCorr,
        miss = miss,
        qq = qq)

    analysis <- anovaNPClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

